# “Git push -f” или после нас хоть потоп

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных.

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией.
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

 С этими библиотеками вы будете знакомится дальше на курсе, а пока давайте попрактикуемся в решении базовых задач на  чистом Python.

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [5]:
def share_bread(N, K):
    # x - количество кусков каждому (целочисленное деление)
    x = K // N
    # y - остаток в корзинке (остаток от деления)
    y = K % N
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [4]:
def leap_year(year):
    # Проверяем условие високосного года
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        text_result = "YOU SHALL PASS"
    else:
        text_result = "YOU SHALL NOT PASS"
    return text_result

assert leap_year(5) == 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>


Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

**Подсказка:** используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [3]:
def amulet_area(a, b, c):
     # 1. Считаем полупериметр
    p = (a + b + c) / 2
    
    # 2. Считаем площадь по формуле Герона
    # Корень извлекаем возведением в степень 0.5
    S = (p * (p - a) * (p - b) * (p - c)) ** 0.5
    return S

assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - написать функцию под каждую из них. Важное условие - используйте только базовые функции для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [10]:
import numpy as np

In [11]:
def cal_euclidean(a, b):
    # Евклидово: корень из суммы квадратов разностей
    distance = sum((ai - bi)**2 for ai, bi in zip(a, b))**0.5
    return distance

def cal_manhattan(a, b):
    # Манхэттен: сумма абсолютных разностей (модулей)
    distance = sum(abs(ai - bi) for ai, bi in zip(a, b))
    return distance

def cal_cosine(a, b):
    # Косинусное: 1 - (скалярное произведение / произведение норм)
    dot_product = sum(ai * bi for ai, bi in zip(a, b))
    norm_a = sum(ai**2 for ai in a)**0.5
    norm_b = sum(bi**2 for bi in b)**0.5
    
    distance = 1 - (dot_product / (norm_a * norm_b))
    return distance

In [12]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

17.88854381999832
44
0.41571161049032157


## Задача 5* (бонусное неоцениваемое задание)

**Замечание:** Поскольку библиотеку numpy мы будем подробно разбирать дальше, то это задание является бонусным, его выполнение необязательно для сдачи ДЗ и не влияет на итоговый балл. Как вариант, можете вернуться к нему после прохождения numpy ;)



Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в интервале от 0 до 1 остаются прежними

In [14]:
# Создаем случайный массив из 100 элементов
raw_array = np.random.rand(100)

# Применяем формулу: (x - min) / (max - min)
my_array = (raw_array - raw_array.min()) / (raw_array.max() - raw_array.min())

print(np.max(my_array), np.min(my_array))
print(my_array)



1.0 0.0
[0.04078385 0.74747664 0.7109453  0.72235698 0.57658432 0.20936256
 0.90674475 0.15327066 0.02502908 0.11407793 0.17729868 0.1597166
 0.89856071 0.34178383 0.19462281 0.58898582 0.71805404 0.4257409
 0.03624297 0.10652815 0.69098043 0.94979973 0.09806184 0.90326465
 0.51519384 0.37196536 0.90561988 0.2427478  0.9520754  0.91177991
 0.90458275 0.23961408 0.77178186 0.96154291 0.21395137 0.58502937
 0.25270058 0.92961964 0.91303986 0.38518593 0.61859571 0.75261349
 0.33897861 0.11858657 0.50459829 0.02778053 0.44393622 0.72828616
 0.06949768 0.12009263 0.78943067 0.13674854 0.1183718  0.43386514
 0.95794088 0.97861869 0.06531535 0.97378428 0.2479814  0.87044885
 0.90184797 0.53266262 0.48456621 0.65863023 0.94779154 0.46049946
 0.94875305 0.4724201  0.05375249 0.06454965 0.18148794 0.05717788
 0.12724015 0.94008384 0.01249594 0.50378952 0.31306496 0.1310853
 0.98074549 0.19129249 0.48304816 0.39552107 0.79335408 0.
 0.62263006 0.38808303 0.74108837 0.98505655 0.85400826 0.5602052

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы

In [16]:
# Создаем матрицу 5x6 с целыми числами от 0 до 50
my_array = np.random.randint(0, 51, size=(5, 6))

# Находим индекс максимального элемента во всей матрице
# np.argmax выдает плоский индекс, поэтому разворачиваем его в координаты (строка, колонка)
row_idx, col_idx = np.unravel_index(np.argmax(my_array), my_array.shape)

# Выбираем всю колонку по найденному индексу
selected_column = my_array[:, col_idx]

print('Shape: ', my_array.shape)
print('Array')
print(my_array)
print(f"Максимум находится в колонке индекс: {col_idx}")
print(selected_column)

Shape:  (5, 6)
Array
[[19 24 13 31 34 30]
 [31 50  0 12 23 28]
 [43  2 24 47 12 44]
 [34 24  5 17 39 19]
 [31  4 37 32 20 19]]
Максимум находится в колонке индекс: 1
[24 50  2 24  4]


Напишите функцию, которая принимает на вход матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [17]:

def get_unique_rows(X):
    # Используем встроенную функцию np.unique с указанием оси 0 (строки)
    X_unique = np.unique(X, axis=0)
    return X_unique

In [18]:
# Тестовый запуск 
X = np.random.randint(4, 6, size=(10, 3))
print("Исходная матрица:")
print(X)


Исходная матрица:
[[5 4 4]
 [5 4 5]
 [4 4 5]
 [4 4 5]
 [5 4 4]
 [5 5 5]
 [5 4 5]
 [4 5 4]
 [4 4 4]
 [4 4 5]]


In [19]:
print("\nУникальные строки:")
print(get_unique_rows(X))


Уникальные строки:
[[4 4 4]
 [4 4 5]
 [4 5 4]
 [5 4 4]
 [5 4 5]
 [5 5 5]]
